from . import id_handlers
from . import text_handlers
from . import regex_handlers
from . import change_lang
from . import hashtag
from . import content_types
from . import admin_handlers
from . import states_handlers
from . import other_handlers
from . import anketa
from . import help
from . import start
from . import echo